### ISSUE TITLE
[:bug: bug report] Failing to Build Fastsweep

### ISSUE THREAD

**Issue by uguuuuuu** [rgl-epfl/fastsweep#1]
When I tried to build fastsweep using `pip install .`, the compiler complained that the `meshgrid()` function in `distance_marcher.cpp` conflicts with the same function in `drjit/util.h`, and the building succeeded after I commented out the `meshgrid()` in `distance_marcher.cpp`. This issue came up after I upgraded the version of Dr.Jit from 0.2.2 to 0.3.2. I am not sure whether it is a bug.

## System configuration

  OS: Ubuntu 20.04
  Python version: 3.9
  CUDA version: 11.7

  Dr.Jit version: 0.3.2
     Compiled with: Clang 12

**Comment by dvicini** [comment]
Thanks, sorry for the delay, it's fixed now
