### ISSUE TITLE
fastsweep requires an older version of drjit to work

### ISSUE THREAD

**Issue by mlamarre** [rgl-epfl/fastsweep#3]
Setup:
* Windows 11
* Mambaforge python 3.10
* Clean environment
* Installed with `pip install fastsweep`

`import fastsweep` gives error `ImportError: DLL load failed while importing _fastsweep_core`

Used a dependency walker to find the issue was with `drjit_core.dll`.

Workaround : 

`pip install drjit==0.2.2`

Solves the issue, I found this version by looking for a build that predates the Pypi fastsweep package.

I think `fastsweep` just needs a rebuild. Thanks!

**Comment by dvicini** [comment]
Hi,
Thanks for letting me know! I will take a look, should be easy to fix.
Delio

**Comment by dvicini** [comment]
Should be fixed now, just released a new version on pypi. 

You can upgrade by running
```
pip install -U fastsweep
```
