### ISSUE TITLE
fastsweep doesn't work with drjit >=1.0

### ISSUE THREAD

**Issue by mlamarre** [rgl-epfl/fastsweep#4]
There's a new version of drjit since last week.
fastsweep has the same error `ImportError: DLL load failed while importing _fastsweep_core`  as last time. 
BTW we cited fastsweep in Siggraph Asia 2024 Tech. Comm (https://arxiv.org/pdf/2411.05827)
Thanks!

**Comment by dvicini** [comment]
Thanks for reporting! I will try to find some time over the coming weeks to update this.

**Comment by dvicini** [comment]
This is fixed now and I've released new PyPi packages that are compatible with Dr.Jit >= 1.0.0.
